const prisma = require("./config/prisma");

async function seedFullDikti() {
  console.log("Hapus pertanyaan DIKTI lama...");
  await prisma.tracerQuestion.deleteMany({ where: { category: "DIKTI" } });

  const diktiQuestions = [
    // DATA PRIBADI
    {
      urutan: 1,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "NIK (Nomor Induk Kependudukan)",
      tipe: "text",
      opsi: "",
      isRequired: true,
      isActive: true,
    },
    {
      urutan: 2,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "NPWP (Jika ada)",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 3,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "Alamat Tempat Tinggal (Nama Jalan)",
      tipe: "text",
      opsi: "",
      isRequired: true,
      isActive: true,
    },
    {
      urutan: 4,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "RT/RW Tempat Tinggal Saat Ini",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 5,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "Kecamatan Tempat Tinggal Saat Ini",
      tipe: "text",
      opsi: "",
      isRequired: true,
      isActive: true,
    },
    {
      urutan: 6,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "Kota/Kabupaten Tempat Tinggal Saat Ini",
      tipe: "text",
      opsi: "",
      isRequired: true,
      isActive: true,
    },
    {
      urutan: 7,
      section: "Data Pribadi",
      category: "DIKTI",
      pertanyaan: "Provinsi Tempat Tinggal Saat Ini",
      tipe: "text",
      opsi: "",
      isRequired: true,
      isActive: true,
    },

    // KUESIONER WAJIB
    {
      urutan: 8,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan: "Pilih salah satu status keberkerjaan Anda saat ini?",
      tipe: "select",
      opsi: "Sudah Bekerja (Penuh/Paruh waktu),Wiraswasta,Melanjutkan Pendidikan,Tidak Kerja tetapi sedang mencari kerja,Belum memungkinkan bekerja",
      isRequired: true,
      isActive: true,
    },
    {
      urutan: 9,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan:
        "Dapatkah Anda menjelaskan faktor penyebab Anda belum memungkinkan bekerja? (Bagi yang menjawab Belum memungkinkan bekerja)",
      tipe: "textarea",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 10,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan:
        "Apakah Anda mendapatkan pekerjaan pertama kurang dari 6 bulan setelah lulus?",
      tipe: "select",
      opsi: "Ya,Tidak Lebih dari 6 bulan",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 11,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan:
        "Jika lebih dari 6 bulan mendapatkan pekerjaan pertama, berapa bulan Anda mencari/mendapatkan pekerjaan?",
      tipe: "select",
      opsi: "6-9 Bulan,9-12 Bulan,12-15 Bulan,Diatas 15 Bulan",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 12,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan:
        "Berapa rata-rata pendapatan Anda perbulan? (Dalam Angka Rupiah)",
      tipe: "select",
      opsi: "Dibawah Rp. 3 Juta,Rp 3-5 Juta,Rp. 5-7,Rp. 7-9,Rp. 9-12,Diatas Rp. 12 Juta",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 13,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan: "Provinsi tempat Anda bekerja?",
      tipe: "select",
      opsi: "Aceh,Sumatera Utara,Sumatera Barat,Riau,Kepulauan Riau,Jambi,Bengkulu,Sumatera Selatan,Kepulauan Bangka Belitung,Lampung,DKI Jakarta,Banten,Jawa Barat,Jawa Tengah,DI Yogyakarta,Jawa Timur,Bali,Nusa Tenggara Barat,Nusa Tenggara Timur,Kalimantan Barat,Kalimantan Tengah,Kalimantan Selatan,Kalimantan Timur,Kalimantan Utara,Sulawesi Utara,Gorontalo,Sulawesi Tengah,Sulawesi Barat,Sulawesi Selatan,Sulawesi Tenggara,Maluku,Maluku Utara,Papua,Papua Barat,Papua Selatan,Papua Tengah,Papua Pegunungan,Papua Barat Daya",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 14,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan: "Kabupaten/Kota tempat Anda bekerja?",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 15,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan:
        "Apa jenis perusahaan/instansi/institusi tempat Anda bekerja sekarang?",
      tipe: "select",
      opsi: "Instansi Pemerintah,BUMN/BUMD,Organisasi Non-Profit/LSM,Perusahaan Swasta,Wiraswasta/Usaha Mandiri,Institusi/Organisasi Multilateral",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 16,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan: "Apa nama perusahaan/kantor tempat Anda bekerja?",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 17,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan: "Bila berwiraswasta, apa posisi/jabatan Anda saat ini?",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 18,
      section: "Kuesioner Wajib Status Keberkerjaan",
      category: "DIKTI",
      pertanyaan: "Apa tingkat tempat kerja Anda?",
      tipe: "select",
      opsi: "Lokal/Wilayah/Berwirausaha tidak berizin,Nasional/Berwirausaha berbadan hukum,Internasional/Multinasional",
      isRequired: false,
      isActive: true,
    },

    // MELANJUTKAN PENDIDIKAN
    {
      urutan: 19,
      section: "Pertanyaan Lanjut Pendidikan",
      category: "DIKTI",
      pertanyaan: "Sumber biaya pendidikan tinggi lanjut?",
      tipe: "select",
      opsi: "Biaya Sendiri,Beasiswa",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 20,
      section: "Pertanyaan Lanjut Pendidikan",
      category: "DIKTI",
      pertanyaan: "Nama Perguruan Tinggi Lanjut",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 21,
      section: "Pertanyaan Lanjut Pendidikan",
      category: "DIKTI",
      pertanyaan: "Program Studi Pendidikan Lanjut",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 22,
      section: "Pertanyaan Lanjut Pendidikan",
      category: "DIKTI",
      pertanyaan: "Tanggal Masuk Pendidikan Lanjut",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 23,
      section: "Pertanyaan Lanjut Pendidikan",
      category: "DIKTI",
      pertanyaan:
        "Sumber dana pembiayaan pada waktu kuliah di Politeknik Negeri Manado",
      tipe: "select",
      opsi: "Biaya sendiri/Keluarga,Beasiswa ADIK,Beasiswa BIDIKMISI/KIP,Beasiswa PPA,Beasiswa AFIRMASI,Beasiswa perusahaan/Swasta",
      isRequired: false,
      isActive: true,
    },

    // KESELARASAN BIDANG & KOMPETENSI
    {
      urutan: 24,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Seberapa erat hubungan bidang studi dengan pekerjaan Anda?",
      tipe: "radio",
      opsi: "Sangat Erat,Erat,Cukup Erat,Kurang Erat,Tidak Erat Sama Sekali",
      isRequired: true,
      isActive: true,
    },
    {
      urutan: 25,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan:
        "Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan Anda saat ini?",
      tipe: "select",
      opsi: "Setingkat lebih tinggi,Tingkat yang sama,Setingkat lebih rendah,Tidak perlu pendidikan tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 26,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan:
        "Pada saat lulus  (A)  , pada tingkat mana kompetensi di bawah ini anda kuasai dan pada tingkat mana kompetensi di bawah ini diperlukan dalam pekerjaan (B)? \n\nBidang Kompetensi  (Pilih jawaban bidang dibawah ini)",
      tipe: "label",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 27,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Etika (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 28,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Etika (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 29,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Keahlian berdasarkan bidang ilmu (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 30,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan:
        "Keahlian berdasarkan bidang ilmu (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 31,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Bahasa Inggris (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 32,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Bahasa Inggris (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 33,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Penggunaan Teknologi Informasi (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 34,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan:
        "Penggunaan Teknologi Informasi (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 35,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Komunikasi (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 36,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Komunikasi (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 37,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Kerja sama tim (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 38,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Kerja sama tim (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 39,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Pengembangan Diri (A - Pada saat lulus)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 40,
      section: "Keselarasan Bidang & Kompetensi",
      category: "DIKTI",
      pertanyaan: "Pengembangan Diri (B - Diperlukan dalam pekerjaan)",
      tipe: "radio",
      opsi: "Sangat Rendah,Rendah,Cukup,Tinggi,Sangat Tinggi",
      isRequired: false,
      isActive: true,
    },

    // METODE PEMBELAJARAN
    {
      urutan: 41,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan:
        "Menurut anda seberapa besar penekanan pada metode pembelajaran dibawah ini dilaksanakan di program studi anda?",
      tipe: "label",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 42,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan: "Perkuliahan / Tatap muka dikelas dengan Dosen (Teori)",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 43,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan: "Demonstrasi/Peragaan",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 44,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan:
        "Partisipasi dalam proyek pembelajaran / penelitian / Pengabdian",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 45,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan: "Magang",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 46,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan: "Praktikum",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 47,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan: "Kerja di Industri",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 48,
      section: "Penekanan Metode Pembelajaran",
      category: "DIKTI",
      pertanyaan: "Diskusi / Studi Kasus",
      tipe: "radio",
      opsi: "Sangat Besar,Besar,Cukup Besar,Kurang Besar,Tidak Sama Sekali",
      isRequired: false,
      isActive: true,
    },

    // PENCARIAN KERJA
    {
      urutan: 49,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan:
        "Kapan Anda mulai mencari pekerjaan? (Sebutkan berapa bulan sebelum/setelah lulus)",
      tipe: "select",
      opsi: "Kira-kira beberapa bulan sebelum lulus,Kira-kira beberapa bulan setelah lulus,Saya tidak mencari kerja",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 50,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan: "Bagaimana Anda mencari pekerjaan tersebut?",
      tipe: "checkbox",
      opsi: "Iklan di koran/majalah/brosur,Melamar ke perusahaan tanpa tahu lowongan,Bursa/Pameran kerja,Internet/Iklan online/Medsos,Dihubungi oleh perusahaan,Menghubungi Kemenaker/Disnaker,Agen tenaga kerja komersial/swasta,Unit Pengembangan Karir Polimdo,Hubungan Alumni/Kemahasiswaan,Membangun jejaring (network) sejak kuliah,Melalui relasi (dosen/orang tua/teman),Membangun bisnis sendiri,Melalui penempatan kerja atau magang,Bekerja di tempat sama sewaktu kuliah,Lainnya",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 51,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan:
        "Berapa perusahaan/instansi yang Anda lamar sebelum memperoleh pekerjaan pertama?",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 52,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan:
        "Berapa banyak perusahaan/instansi yang merespons lamaran Anda?",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 53,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan:
        "Berapa banyak perusahaan/instansi yang mengundang Anda untuk wawancara?",
      tipe: "text",
      opsi: "",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 54,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan:
        "Apakah Anda aktif mencari pekerjaan dalam 4 minggu terakhir?",
      tipe: "checkbox",
      opsi: "Tidak,Tidak tapi saya sedang menunggu hasil lamaran kerja,Ya saya akan mulai bekerja dalam 2 minggu ke depan,Ya tapi saya belum pasti akan bekerja dalam 2 minggu ke depan",
      isRequired: false,
      isActive: true,
    },
    {
      urutan: 55,
      section: "Pencarian Kerja",
      category: "DIKTI",
      pertanyaan:
        "Jika pekerjaan saat ini tidak sesuai dengan pendidikan Anda, mengapa Anda mengambilnya?",
      tipe: "select",
      opsi: "Pekerjaan saya sekarang sudah sesuai dengan pendidikan,Belum mendapatkan pekerjaan yang lebih sesuai,Prospek karir yang baik,Suka pekerjaan yang tidak berhubungan dengan pendidikan,Dipromosikan ke posisi kurang berhubungan dengan pendidikan,Pendapatan lebih tinggi,Pekerjaan lebih aman/terjamin,Pekerjaan lebih menarik,Lokasi lebih dekat dari rumah,Kebutuhan keluarga lebih terjamin,Harus menerima pekerjaan tidak berhubungan pada awal karir,Lainnya",
      isRequired: false,
      isActive: true,
    },
  ];

  for (const q of diktiQuestions) {
    await prisma.tracerQuestion.create({ data: q });
  }

  console.log(
    `Berhasil menambahkan ${diktiQuestions.length} pertanyaan DIKTI lengkap!`,
  );
}

seedFullDikti().then(() => process.exit(0));
